### ISSUE TITLE
build failed(win10, vs2019)

### ISSUE THREAD

**Issue by zuixiaosanlang** [IDLabMedia/image-lens-reproject#2]
![image](https://user-images.githubusercontent.com/20105627/175505059-5a22267f-31d1-4824-96bc-e7763a515090.png)

**Comment by procrastinando** [comment]
I have the same issue, so I had to use WSL2.

**Comment by mcourteaux** [comment]
I'm sorry I missed your original question. Since then I made automatic builds using Github CI, and uncovered indeed some compilation problems. Those should be taken care of by now. Best regards, Martijn.
