### ISSUE TITLE
Where is ./reproject?

### ISSUE THREAD

**Issue by procrastinando** [IDLabMedia/image-lens-reproject#3]
I have succesfully built image lens reproject, but, I cant find reproject to run

**Comment by mcourteaux** [comment]
Sorry I missed your question. We have updated the build process. Additionally there are releases available for download in the [Releases](https://github.com/IDLabMedia/image-lens-reproject/releases) here on Github. The files can be found typically in a `bin` folder after you have compiled them yourself.
