### ISSUE TITLE
Cant build on Windows 10

### ISSUE THREAD

**Issue by MartinMisiak** [IDLabMedia/image-lens-reproject#4]
Unfortunately i had no luck building the project on Windows 10 with either VS2017,19,2022 or GCC via MinGW. 
What kind of compiler and which OS are tested to be working for this project ?

**Comment by mcourteaux** [comment]
I'm sorry I initially missed your question. We went through the trouble of trying to compile this for Windows ourselves. The project is updated and should work smoothly for Windows too now. Moreover, we have make Github actions, and have automatic compiled releases. So head over to the [Releases](https://github.com/IDLabMedia/image-lens-reproject/releases) to find a build for Windows! :smile: 

Make sure to also update the git submodules with:

```sh
git submodule update
```

**Comment by mcourteaux** [comment]
Feel free to reply below in case of any trouble. I should get notifications from this repo now. Will close, as I assume it's fixed.
