### ISSUE TITLE
Error with submodule

### ISSUE THREAD

**Issue by NiklasVoigt** [IDLabMedia/image-lens-reproject#5]
[submodule "lib/cxxopts"]
	path = lib/cxxopts
	url = https://github.com/mcourteaux/cxxopts

can't initialize this submodule. maybe its private/deleted?

**Comment by mcourteaux** [comment]
Thanks for pointing that out. The original repository had a bug, so I patched it, and while waiting for the PR to merge, I changed this to my own fork. Will update right now!

**Comment by mcourteaux** [comment]
Let me know if you still have trouble with this :)
